import { NextResponse } from 'next/server'
import PptxGenJS from 'pptxgenjs'
import { Document, HeadingLevel, Packer, Paragraph } from 'docx'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { sql } from 'drizzle-orm'
import { db } from '@/lib/db'

export const runtime = 'nodejs'
const telegramApi = () => `https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}`
type Stage = 'topic' | 'type' | 'language' | 'level' | 'slides' | 'author' | 'title'
type Session = { stage: Stage; topic?: string; type?: 'slide' | 'work' | 'both'; language?: string; level?: string; slides?: number; author?: string; title?: boolean }
type Content = { title: string; subtitle: string; introduction: string; sections: { heading: string; body: string; bullets: string[] }[]; conclusion: string; sources: string[] }

async function telegram(method: string, body: FormData | Record<string, unknown>) { const form = body instanceof FormData; return fetch(`${telegramApi()}/${method}`, { method: 'POST', headers: form ? undefined : { 'content-type': 'application/json' }, body: form ? body : JSON.stringify(body) }) }
async function sendMessage(chatId: number, text: string, keyboard?: object) { return telegram('sendMessage', { chat_id: chatId, text, ...(keyboard ? { reply_markup: keyboard } : {}) }) }
const keyboard = (rows: string[][]) => ({ keyboard: rows.map((row) => row.map((text) => ({ text }))), resize_keyboard: true, one_time_keyboard: true })
async function sendDocument(chatId: number, bytes: Uint8Array, name: string, caption: string) { const form = new FormData(); form.append('chat_id', String(chatId)); form.append('document', new Blob([bytes as unknown as BlobPart]), name); form.append('caption', caption); return telegram('sendDocument', form) }

async function getUser(chatId: number, message: any) { const first = String(message.from?.first_name || ''); const last = String(message.from?.last_name || ''); const username = message.from?.username ? String(message.from.username) : null; const result = await db.execute(sql`INSERT INTO telegram_users (telegram_id, username, first_name, last_name) VALUES (${chatId}, ${username}, ${first}, ${last}) ON CONFLICT (telegram_id) DO UPDATE SET username=${username}, first_name=${first}, last_name=${last}, updated_at=NOW() RETURNING telegram_id, balance, bonus_claimed, state`); return result.rows[0] as any }
async function saveState(chatId: number, state: Session) { await db.execute(sql`UPDATE telegram_users SET state=${JSON.stringify(state)}::jsonb, updated_at=NOW() WHERE telegram_id=${chatId}`) }
async function clearState(chatId: number) { await db.execute(sql`UPDATE telegram_users SET state='{}'::jsonb, updated_at=NOW() WHERE telegram_id=${chatId}`) }
async function setting(key: string, fallback: number | string) { const result = await db.execute(sql`SELECT value FROM edumaker_settings WHERE key=${key}`); const value = (result.rows[0] as any)?.value; return value?.value ?? fallback }

async function generateContent(session: Session): Promise<Content> { const key = process.env.GROQ_API_KEY || process.env.GEMINI_API_KEY; const groq = Boolean(process.env.GROQ_API_KEY); if (key) { const endpoint = groq ? 'https://api.groq.com/openai/v1/chat/completions' : 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions'; const response = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${key}` }, body: JSON.stringify({ model: groq ? 'llama-3.3-70b-versatile' : 'gemini-2.0-flash', temperature: 0.35, response_format: { type: 'json_object' }, messages: [{ role: 'system', content: 'You are a professional Uzbek academic editor. Return JSON only: title,subtitle,introduction,sections[{heading,body,bullets}],conclusion,sources. Make original, factually careful, presentation-ready content.' }, { role: 'user', content: `Mavzu: ${session.topic}; Til: ${session.language}; Daraja: ${session.level}; Bo'limlar: ${session.slides}; Tur: ${session.type}` }] }) }); if (response.ok) { const data = await response.json(); return JSON.parse(data.choices?.[0]?.message?.content || '{}') } } return { title: session.topic || 'Mavzu', subtitle: 'EduMaker akademik materiali', introduction: `${session.topic} mavzusi bo‘yicha kirish.`, sections: Array.from({ length: session.slides || 8 }, (_, i) => ({ heading: `${i + 1}-bo‘lim`, body: `${session.topic} bo‘yicha asosiy nazariy va amaliy ma’lumotlar.`, bullets: ['Asosiy tushuncha', 'Amaliy ahamiyati', 'Tahliliy xulosa'] })), conclusion: 'Mavzu bo‘yicha asosiy fikrlar umumlashtirildi.', sources: ['O‘quv qo‘llanmalar va ilmiy manbalar'] } }
async function createPptx(content: Content, title: boolean) { const pptx = new PptxGenJS(); pptx.layout = 'LAYOUT_WIDE'; const add = (h: string, b: string, bullets: string[] = []) => { const s = pptx.addSlide(); s.background = { color: 'F7FAFC' }; s.addText(h, { x: .7, y: .55, w: 11.8, h: .6, fontSize: 25, bold: true, color: '102A43' }); s.addText(b, { x: .75, y: 1.45, w: 11, h: 1.1, fontSize: 16, color: '334E68' }); if (bullets.length) s.addText(bullets.map((x) => ({ text: x, options: { bullet: { indent: 14 } } })), { x: .9, y: 2.9, w: 10.8, h: 2.2, fontSize: 18, color: '243B53', breakLine: true }) }; if (title) { const s = pptx.addSlide(); s.background = { color: '102A43' }; s.addText(content.title, { x: .9, y: 2.2, w: 11, h: 1, fontSize: 34, bold: true, color: 'FFFFFF', align: 'center' }); s.addText(content.subtitle, { x: 1.2, y: 3.55, w: 10.4, h: .5, fontSize: 18, color: 'BEE3F8', align: 'center' }) } add('Kirish', content.introduction); content.sections.forEach((s) => add(s.heading, s.body, s.bullets)); add('Xulosa', content.conclusion, content.sources); return pptx.write({ outputType: 'nodebuffer' }) as Promise<Uint8Array> }
async function createDocx(content: Content, title: boolean) { const children = [...(title ? [new Paragraph({ text: content.title, heading: HeadingLevel.TITLE }), new Paragraph(content.subtitle)] : []), new Paragraph({ text: 'Kirish', heading: HeadingLevel.HEADING_1 }), new Paragraph(content.introduction), ...content.sections.flatMap((s) => [new Paragraph({ text: s.heading, heading: HeadingLevel.HEADING_1 }), new Paragraph(s.body), ...s.bullets.map((b) => new Paragraph({ text: b, bullet: { level: 0 } }))]), new Paragraph({ text: 'Xulosa', heading: HeadingLevel.HEADING_1 }), new Paragraph(content.conclusion)]; return Packer.toBuffer(new Document({ sections: [{ children }] })) }
async function createPdf(content: Content, title: boolean) { const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); let page = pdf.addPage([595, 842]); let y = 790; const write = (text: string, size = 12) => { for (const line of text.match(/.{1,82}(\s|$)/g) || [text]) { if (y < 70) { page = pdf.addPage([595, 842]); y = 790 } page.drawText(line.trim(), { x: 48, y, size, font, color: rgb(.1, .2, .3) }); y -= size + 8 } }; if (title) write(content.title, 22); write(content.introduction); content.sections.forEach((s) => { write(s.heading, 16); write(s.body); s.bullets.forEach((b) => write('• ' + b)) }); write('Xulosa', 16); write(content.conclusion); return pdf.save() }

export async function POST(request: Request) { if (!process.env.TELEGRAM_BOT_TOKEN) return NextResponse.json({ error: 'Bot token is not configured' }, { status: 500 }); const update = await request.json(); const message = update?.message; const chatId = message?.chat?.id as number | undefined; if (!chatId) return NextResponse.json({ ok: true }); const text = String(message.text ?? '').trim(); const user = await getUser(chatId, message); const state = user.state?.stage ? user.state as Session : null
  if (text === '/start') { const bonus = !user.bonus_claimed; if (bonus) await db.execute(sql`UPDATE telegram_users SET bonus_claimed=TRUE, balance=balance+2000 WHERE telegram_id=${chatId}`); await sendMessage(chatId, `Assalomu alaykum, ${message.from?.first_name || 'foydalanuvchi'}! EduMaker Bot professional slayd va mustaqil ish yaratadi.\n\nBalansingiz: ${Number(user.balance || 0) + (bonus ? 2000 : 0)} so‘m${bonus ? '\nBonus: +2 000 so‘m' : ''}`, keyboard([['Yangi ish yaratish'], ['Balansim', 'Profil'], ['Balansni to‘ldirish']])); return NextResponse.json({ ok: true }) }
  if (text === 'Balansim') { await sendMessage(chatId, `Balansingiz: ${user.balance} so‘m\n1 slayd narxi: ${await setting('slide_price', 2000)} so‘m`, keyboard([['Yangi ish yaratish'], ['Balansni to‘ldirish'], ['Profil']])); return NextResponse.json({ ok: true }) }
  if (text === 'Profil') { await sendMessage(chatId, `Profil\nIsm: ${user.first_name || '-'}\nUsername: @${user.username || '-'}\nTelegram ID: ${chatId}\nBonus ishlatilgan: ${user.bonus_claimed ? 'ha' : 'yo‘q'}`, keyboard([['Yangi ish yaratish'], ['Balansim']])); return NextResponse.json({ ok: true }) }
  if (text === 'Balansni to‘ldirish') { await sendMessage(chatId, 'Balans to‘ldirish uchun admin bilan bog‘laning. To‘lov cheki va Telegram ID yuboring.'); return NextResponse.json({ ok: true }) }
  if (text === 'Yangi ish yaratish' || text === '/new') { await saveState(chatId, { stage: 'topic' }); await sendMessage(chatId, 'Mavzuni yuboring:', keyboard([['Bekor qilish']])); return NextResponse.json({ ok: true }) }
  if (text === 'Bekor qilish') { await clearState(chatId); await sendMessage(chatId, 'Bekor qilindi.', keyboard([['Yangi ish yaratish'], ['Balansim', 'Profil']])); return NextResponse.json({ ok: true }) }
  if (!state) { await sendMessage(chatId, 'Menyudan tanlang yoki /start yuboring.', keyboard([['Yangi ish yaratish'], ['Balansim', 'Profil']])); return NextResponse.json({ ok: true }) }
  if (state.stage === 'topic') { state.topic = text; state.stage = 'type'; await sendMessage(chatId, 'Ish turini tanlang:', keyboard([['Slayd', 'Mustaqil ish'], ['Slayd + Mustaqil ish'], ['Bekor qilish']])) }
  else if (state.stage === 'type') { state.type = text.includes('Mustaqil') && text.includes('Slayd') ? 'both' : text.includes('Mustaqil') ? 'work' : 'slide'; state.stage = 'language'; await sendMessage(chatId, 'Tilni tanlang:', keyboard([['O‘zbek', 'Русский', 'English']])) }
  else if (state.stage === 'language') { state.language = text.includes('Рус') ? 'Russian' : text.includes('English') ? 'English' : 'Uzbek'; state.stage = 'level'; await sendMessage(chatId, 'Ta’lim darajasi yoki sinfni yozing:') }
  else if (state.stage === 'level') { state.level = text; state.stage = 'slides'; await sendMessage(chatId, 'Nechta slayd/bo‘lim kerak?', keyboard([['6', '8', '10', '12'], ['Bekor qilish']])) }
  else if (state.stage === 'slides') { state.slides = Math.max(6, Math.min(20, Number.parseInt(text, 10) || 8)); state.stage = 'author'; await sendMessage(chatId, 'Titul sahifasi kerakmi?', keyboard([['Ha, ismni kiritaman'], ['Yo‘q, titul kerak emas'], ['Bekor qilish']])) }
  else if (state.stage === 'author') { if (text.startsWith('Yo‘q')) { state.title = false; state.stage = 'title' } else { state.title = true; state.stage = 'title'; await sendMessage(chatId, 'Titul uchun ism-familiya va fan nomini yozing:') } if (!text.startsWith('Yo‘q')) { await saveState(chatId, state); return NextResponse.json({ ok: true }) } }
  else if (state.stage === 'title') { if (state.title && !state.author) state.author = text; await saveState(chatId, { ...state, stage: 'author' }); await sendMessage(chatId, 'Tayyorlanmoqda...'); try { const price = Number(await setting('slide_price', 2000)); const current = Number((await getUser(chatId, message)).balance || 0); const cost = (state.slides || 8) * price; if (current < cost) { await sendMessage(chatId, `Balans yetarli emas. Kerak: ${cost} so‘m, mavjud: ${current} so‘m.`, keyboard([['Balansni to‘ldirish'], ['Yangi ish yaratish']])); return NextResponse.json({ ok: true }) } const content = await generateContent(state); if (state.author) content.subtitle += `\n${state.author}`; const [pptx, docx, pdf] = await Promise.all([createPptx(content, Boolean(state.title)), createDocx(content, Boolean(state.title)), createPdf(content, Boolean(state.title))]); if (state.type !== 'work') await sendDocument(chatId, pptx, `${content.title}.pptx`, 'Professional taqdimot tayyor'); if (state.type !== 'slide') { await sendDocument(chatId, docx, `${content.title}.docx`, 'Mustaqil ish tayyor'); await sendDocument(chatId, pdf, `${content.title}.pdf`, 'PDF nusxa tayyor') } await db.execute(sql`UPDATE telegram_users SET balance=balance-${cost}, state='{}'::jsonb, updated_at=NOW() WHERE telegram_id=${chatId}`); await sendMessage(chatId, `Tayyor. ${cost} so‘m yechildi. Qolgan balansingizni “Balansim” tugmasi orqali ko‘ring.`, keyboard([['Yangi ish yaratish'], ['Balansim', 'Profil']])); } catch (error) { console.error('[v0] Generation failed:', error); await sendMessage(chatId, 'Fayl yaratishda xatolik yuz berdi. Keyinroq qayta urinib ko‘ring.') } }
  return NextResponse.json({ ok: true }) }
export async function GET() { return NextResponse.json({ service: 'EduMaker Telegram webhook', configured: Boolean(process.env.TELEGRAM_BOT_TOKEN), databaseConfigured: Boolean(process.env.DATABASE_URL), aiConfigured: Boolean(process.env.GROQ_API_KEY || process.env.GEMINI_API_KEY) }) }
